name: flutter_green_track
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  get: ^4.6.6
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  table_calendar: ^3.2.0
  flutter_animate: ^4.5.2
  fl_chart: ^0.69.0
  barcode_scan2: ^4.5.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  image_picker: ^1.1.2
  uuid: ^4.5.1
  http: ^1.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  qr_flutter: ^4.1.0
  image_gallery_saver_plus: ^4.0.1
  shimmer: ^3.0.0
  torch_light: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
  - assets/icon/ic_app.png
