name: flutter_green_track
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  get: ^4.6.6
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  table_calendar: ^3.2.0
  flutter_animate: ^4.5.2
  fl_chart: ^0.69.0
  barcode_scan2: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icon/ic_app.png
